window.MJB_TRANSLATIONS = {
  languages: {
    en: 'English',
    zh: '中文',
    id: 'Bahasa Indonesia'
  },

  en: {
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.location': 'Location',
    'nav.clients': 'Clients',
    'nav.contact': 'Contact',

    'cta.contactUs': 'Contact Us',
    'cta.exploreServices': 'Explore Services',

    'hero.title': 'Integrated Logistics, Depot & Customs Solutions',
    'hero.desc': 'Supporting reliable cargo movement through container depot, ISO tank depot, transportation, customs brokerage, and warehousing services.',

    'services.title': 'Services',
    'services.intro': 'Select a service to view more details about our operational capabilities.',
    'services.containerDepot.title': 'Container Depot',
    'services.containerDepot.desc': 'Our depot offers secure and efficient container storage and maintenance.',
    'services.isoTank.title': 'ISO Tank Depot',
    'services.isoTank.desc': 'Specialized storage and maintenance for ISO tanks.',
    'services.trucking.title': 'Trucking & Transportation',
    'services.trucking.desc': 'Reliable trucking and transportation services for goods and containers.',
    'services.customs.title': 'Customs Brokerage',
    'services.customs.desc': 'Expert customs clearance and documentation handling.',
    'services.logistics.title': 'Logistics',
    'services.logistics.desc': 'Complete logistics option.',
    'services.warehousing.title': 'Warehousing',
    'services.warehousing.desc': 'Complete warehouse storage options.',

    'about.label': 'About',
    'about.title': 'Decades of experience supporting international trade',
    'about.desc': 'Founded in 1985, MJB has expanded from freight forwarding and customs services into depot, isotank and logistics operations to support evolving cargo demands.',
    'about.founded': 'Founded',
    'about.expanded': 'Expanded into Container Depot Services',
    'about.isotank': 'Established Isotank Depot Capability',

    'location.label': 'Location',
    'location.title': 'Strategically located in Belawan',
    'location.desc': 'Our operations are based in Belawan, North Sumatra — one of Indonesia’s key port areas, enabling efficient access to international shipping routes, container handling, and logistics infrastructure.',
    'location.depot': 'Belawan Depot',
    'location.address': 'Jalan Raya Pelabuhan Gabion, Belawan<br>North Sumatra, Indonesia',
    'location.map': 'View on Google Maps →',

    'clients.label': 'Clients',
    'clients.title': 'Trusted by our partners',
    'clients.desc': 'We work with a range of clients across logistics, shipping, and industrial sectors.',

    'contact.title': 'Need a logistics partner?',
    'contact.callUs': 'Call Us',
    'contact.emailUs': 'Email Us',
    'contact.panelTitle': 'Contact Our Offices',
    'contact.medan': 'Medan',
    'contact.belawan': 'Belawan',
    'contact.emailBelawan': 'Email (Belawan)',
    'contact.call': 'Call',
    'contact.email': 'Email',
    'contact.close': 'Close'
  },

  zh: {
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.location': '地点',
    'nav.clients': '客户',
    'nav.contact': '联系',

    'cta.contactUs': '联系我们',
    'cta.exploreServices': '查看服务',

    'hero.title': '综合物流、堆场与报关解决方案',
    'hero.desc': '提供可靠的货物流转支持，涵盖集装箱堆场、ISO 罐箱堆场、运输、报关与仓储服务。',

    'services.title': '服务',
    'services.intro': '选择服务项目以查看我们的运营能力详情。',
    'services.containerDepot.title': '集装箱堆场',
    'services.containerDepot.desc': '我们的堆场提供安全高效的集装箱存放与维护服务。',
    'services.isoTank.title': 'ISO 罐箱堆场',
    'services.isoTank.desc': '为 ISO 罐箱提供专业的存放与维护服务。',
    'services.trucking.title': '卡车运输',
    'services.trucking.desc': '为货物与集装箱提供可靠的卡车运输服务。',
    'services.customs.title': '报关服务',
    'services.customs.desc': '提供专业的清关与报关文件处理服务。',
    'services.logistics.title': '物流服务',
    'services.logistics.desc': '提供完整的物流解决方案。',
    'services.warehousing.title': '仓储服务',
    'services.warehousing.desc': '提供完整的仓储存放方案。',

    'about.label': '关于我们',
    'about.title': '数十年国际贸易支持经验',
    'about.desc': 'MJB 成立于 1985 年，最初专注于货运代理与报关服务，随后扩展至堆场、ISO 罐箱与综合物流业务，以满足不断变化的货运需求。',
    'about.founded': '公司成立',
    'about.expanded': '拓展至集装箱堆场服务',
    'about.isotank': '建立 ISO 罐箱堆场能力',

    'location.label': '地点',
    'location.title': '战略布局于勿拉湾',
    'location.desc': '我们的业务位于印度尼西亚北苏门答腊勿拉湾——该地区是印尼重要港口之一，可高效连接国际航线、集装箱操作与物流基础设施。',
    'location.depot': '勿拉湾堆场',
    'location.address': 'Jalan Raya Pelabuhan Gabion, Belawan<br>North Sumatra, Indonesia',
    'location.map': '在 Google 地图查看 →',

    'clients.label': '客户',
    'clients.title': '合作伙伴的信赖之选',
    'clients.desc': '我们服务于物流、航运及工业领域的多类客户。',

    'contact.title': '需要可靠的物流合作伙伴？',
    'contact.callUs': '致电我们',
    'contact.emailUs': '发送邮件',
    'contact.panelTitle': '联系我们的办公室',
    'contact.medan': '棉兰',
    'contact.belawan': '勿拉湾',
    'contact.emailBelawan': '电子邮箱（勿拉湾）',
    'contact.call': '拨打',
    'contact.email': '邮件',
    'contact.close': '关闭'
  },

  id: {
    'nav.home': 'Beranda',
    'nav.about': 'Tentang',
    'nav.services': 'Layanan',
    'nav.location': 'Lokasi',
    'nav.clients': 'Klien',
    'nav.contact': 'Kontak',

    'cta.contactUs': 'Hubungi Kami',
    'cta.exploreServices': 'Lihat Layanan',

    'hero.title': 'Solusi Logistik, Depot & Kepabeanan Terpadu',
    'hero.desc': 'Mendukung pergerakan kargo yang andal melalui layanan depo kontainer, depo ISO tank, transportasi, customs brokerage, dan pergudangan.',

    'services.title': 'Layanan',
    'services.intro': 'Pilih layanan untuk melihat lebih detail kemampuan operasional kami.',
    'services.containerDepot.title': 'Depo Kontainer',
    'services.containerDepot.desc': 'Depo kami menyediakan penyimpanan dan perawatan kontainer yang aman dan efisien.',
    'services.isoTank.title': 'Depo ISO Tank',
    'services.isoTank.desc': 'Penyimpanan dan perawatan khusus untuk ISO tank.',
    'services.trucking.title': 'Truk & Transportasi',
    'services.trucking.desc': 'Layanan truk dan transportasi yang andal untuk barang dan kontainer.',
    'services.customs.title': 'Jasa Kepabeanan',
    'services.customs.desc': 'Layanan ahli untuk customs clearance dan pengurusan dokumen.',
    'services.logistics.title': 'Logistik',
    'services.logistics.desc': 'Pilihan logistik yang lengkap.',
    'services.warehousing.title': 'Pergudangan',
    'services.warehousing.desc': 'Pilihan penyimpanan gudang yang lengkap.',

    'about.label': 'Tentang',
    'about.title': 'Puluhan tahun pengalaman mendukung perdagangan internasional',
    'about.desc': 'Didirikan pada tahun 1985, MJB berkembang dari freight forwarding dan jasa kepabeanan menjadi operasi depo, isotank, dan logistik untuk mendukung kebutuhan kargo yang terus berkembang.',
    'about.founded': 'Didirikan',
    'about.expanded': 'Berkembang ke Layanan Depo Kontainer',
    'about.isotank': 'Membangun Kapabilitas Depo Isotank',

    'location.label': 'Lokasi',
    'location.title': 'Berlokasi strategis di Belawan',
    'location.desc': 'Operasi kami berbasis di Belawan, Sumatera Utara — salah satu kawasan pelabuhan utama di Indonesia, yang memungkinkan akses efisien ke rute pelayaran internasional, penanganan kontainer, dan infrastruktur logistik.',
    'location.depot': 'Depo Belawan',
    'location.address': 'Jalan Raya Pelabuhan Gabion, Belawan<br>North Sumatra, Indonesia',
    'location.map': 'Lihat di Google Maps →',

    'clients.label': 'Klien',
    'clients.title': 'Dipercaya oleh para mitra kami',
    'clients.desc': 'Kami bekerja dengan berbagai klien di sektor logistik, pelayaran, dan industri.',

    'contact.title': 'Butuh mitra logistik?',
    'contact.callUs': 'Telepon Kami',
    'contact.emailUs': 'Email Kami',
    'contact.panelTitle': 'Hubungi Kantor Kami',
    'contact.medan': 'Medan',
    'contact.belawan': 'Belawan',
    'contact.emailBelawan': 'Email (Belawan)',
    'contact.call': 'Telepon',
    'contact.email': 'Email',
    'contact.close': 'Tutup'
  }
};